app = 'thr3a-discord'
primary_region = 'nrt'

[build]
dockerfile = 'Dockerfile.discord'

[[services]]
auto_stop_machines = 'off'
min_machines_running = 1
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
