import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript, Container, Title } from '@mantine/core';
import type { Metadata } from 'next';
import { theme } from '@/theme';
import { Providers } from '@/providers';
import { headers } from 'next/headers';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export async function generateMetadata (): Promise<Metadata> {
  const csrfToken = headers().get('X-CSRF-Token') ?? 'missing';
  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
    other: {
      'x-csrf-token': csrfToken
    }
  };
}

export default function RootLayout ({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="ja">
      <head>
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Providers>
            <Container pl={0} pr={0}>
              <Title mt={'md'}>Create Next App</Title>
              <Title order={5} mb={'md'} c={'dimmed'}>nyaa</Title>
              {children}
            </Container>
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
