name: Build and Deploy to Fly.io
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [misc-ai, thr3a-discord]
        include:
          - app: misc-ai
            dockerfile: Dockerfile.main
          - app: thr3a-discord
            dockerfile: Dockerfile.discord
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ${{ matrix.dockerfile }}
          push: true
          provenance: false
          tags: ghcr.io/${{ github.actor }}/${{ matrix.app }}:${{ github.sha }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --ha=false -a ${{ matrix.app }} --image ghcr.io/${{ github.actor }}/${{ matrix.app }}:${{ github.sha }}

      - name: Scale Fly.io app
        run: flyctl scale count 1 --region nrt --yes -a ${{ matrix.app }}
